# Generated by Django 3.0.5 on 2020-04-24 22:26

import audiofield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Test',
            fields=[
                ('title', models.CharField(max_length=32)),
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_owner', models.CharField(max_length=32)),
                ('audio_file', audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='your/upload/dir')),
            ],
        ),
        migrations.DeleteModel(
            name='Test_my',
        ),
    ]
